
- name: install common software
  yum:
    name: "{{item}}"
  with_items:
  - rsync
  - docker

- name: create common directory
  file: path="{{item}}" state=directory
  with_items:
  - /root/software
  - /etc/kubernetes
  - /etc/kubernetes/ssl

- name: add local ssh public key
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/k8s_rsa.pub') }}"

- name: get k8s server bin
  synchronize: src="{{item.src}}" dest="{{item.dest}}"
  delegate_to: "{{groups['main'][0]}}"
  with_items:
    - { src: "/root/software/kubernetes-server-linux-amd64.tar.gz", dest: "/root/software/"}
  when: inventory_hostname != groups["main"][0]

#- name: get k8s server bin
#  get_url: 
#    url: "{{item.url}}"
#    dest: "{{item.dest}}" 
#  with_items:
#    - {url: 'http://kubernetes-server-linux-amd64.tar.gz', dest: '/root/software/'}
#  when: inventory_hostname != groups["main"][0]

- name: put k8s server bin
  shell: |
    cd /root/software
    tar -xzvf kubernetes-server-linux-amd64.tar.gz
    cd kubernetes
    tar -xzvf  kubernetes-src.tar.gz
    cp -r server/bin/{kube-apiserver,kube-controller-manager,kube-scheduler,kubectl,kube-proxy,kubelet} /usr/local/bin/
  args:
    executable: /bin/bash

