
- name: approve kubelet csr
  shell: for i in $(kubectl get csr | grep Pending | awk '{ print $1 }' ) ; do kubectl certificate approve $i; done

- name: create addon directory
  file: path="{{item}}" state=directory
  with_items:
  - /root/addon/dns

- name: copy config file
  copy: 
    src: "{{item}}"
    dest: "/root/addon/dns"
  with_fileglob:
    "*.yaml"

- name: generate config by template
  template: src="{{item.src}}" dest="{{item.dest}}"
  with_items:
    - {src: "kubedns-controller.yaml.j2", dest: "/root/addon/dns/kubedns-controller.yaml"}

- name: apply dns resource
  shell: kubectl apply -f /root/addon/dns

