
- name: create addon directory
  file: path="{{item}}" state=directory
  with_items:
  - /root/addon/echo

- name: generate config by template
  template: src="{{item}}" dest="/root/addon/echo"
  with_fileglob:
    "../templates/*.yaml"

- name: apply resource
  shell: kubectl apply -f /root/addon/echo

